version: "3.7"

services:
  jupyter:
    image: jupyter/datascience-notebook
    volumes:
      - ${HOME}/docker/jupyter:/home/jovyan
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
            - 8888:8888
